apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsgo-app-local
  namespace: argocd
  annotations:
    # ArgoCD Image Updater annotations
    argocd-image-updater.argoproj.io/image-list: website-backend,website-frontend
    argocd-image-updater.argoproj.io/website-backend.image-spec: janithasulakshana/website-backend
    argocd-image-updater.argoproj.io/website-backend.update-strategy: semver:~1.0
    argocd-image-updater.argoproj.io/website-backend.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+(-[a-f0-9]{7})?$
    argocd-image-updater.argoproj.io/website-frontend.image-spec: janithasulakshana/website-frontend
    argocd-image-updater.argoproj.io/website-frontend.update-strategy: semver:~1.0
    argocd-image-updater.argoproj.io/website-frontend.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+(-[a-f0-9]{7})?$
spec:
  project: default
  
  source:
    repoURL: https://github.com/janithasulakshana/Website.git
    targetRevision: main
    path: .
    directory:
      recurse: true
      include: '{deployment-*.yaml,secret-app.yaml}'
      exclude: '{argocd-*,docker-compose*,github-actions-*,kustomization-*,pod.yaml}'
    
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

