---
# Namespace for ArgoCD
apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
# ServiceAccount for Image Updater
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd

---
# ClusterRole for Image Updater
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-image-updater
rules:
  # Read ArgoCD Applications
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
    verbs:
      - get
      - list
      - watch
  # Read secrets and configmaps for credentials
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-image-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-image-updater
subjects:
  - kind: ServiceAccount
    name: argocd-image-updater
    namespace: argocd

---
# ConfigMap for Image Updater Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd
data:
  # Log level: trace, debug, info, warn, error
  log.level: info
  
  # Git configuration
  git.user: "argocd-image-updater"
  git.email: "argocd-image-updater@letsgo.local"
  git.commit-message-template: |
    auto: update {{.AppName}} image
    
    {{range .Images}}
    - {{.ImageName}}: {{.OldTag}} → {{.NewTag}}
    {{end}}
  
  # ArgoCD Server configuration
  argocd.server.insecure: "false"
  argocd.grpc.web: "true"
  argocd.server.plaintext: "false"
  
  # Image registry polling interval (in minutes)
  registries.conf: |
    registries:
    - name: Docker Hub
      prefix: docker.io
      api_url: https://registry-1.docker.io
      credentials: secret:dockerhub#credentials
      default: true
    - name: Private Registry
      prefix: your-registry
      api_url: https://your-registry
      credentials: secret:private-registry#credentials

---
# Secret for GitHub/GitLab Token (for pushing commits)
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
type: Opaque
stringData:
  # GitHub Personal Access Token (with repo and read:packages scopes)
  git.token: "ghp_YOUR_GITHUB_TOKEN_HERE"

---
# Secret for Docker Hub credentials (if images are private)
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-credentials
  namespace: argocd
type: Opaque
stringData:
  username: "your-dockerhub-username"
  password: "your-dockerhub-password"

---
# Secret for Private Registry credentials
apiVersion: v1
kind: Secret
metadata:
  name: private-registry-credentials
  namespace: argocd
type: Opaque
stringData:
  username: "your-registry-username"
  password: "your-registry-password"

---
# Deployment for ArgoCD Image Updater
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v0.12.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-image-updater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-image-updater
    spec:
      serviceAccountName: argocd-image-updater
      automountServiceAccountToken: true
      containers:
      - name: argocd-image-updater
        image: argoproj/argocd-image-updater:v0.12.2
        imagePullPolicy: Always
        args:
          - /usr/local/bin/argocd-image-updater
          - run
        
        env:
        # ArgoCD server connection
        - name: ARGOCD_GRPC_WEB
          value: "true"
        - name: ARGOCD_SERVER
          value: "argocd-server.argocd:443"
        
        # Git credentials
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: git.token
        
        # Logging
        - name: IMAGE_UPDATER_LOG_LEVEL
          value: "info"
        
        ports:
        - containerPort: 8080
          name: metrics
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        
        volumeMounts:
        - name: config
          mountPath: /etc/argocd-image-updater
        - name: ssh-keys
          mountPath: /home/argocd-image-updater/.ssh
          readOnly: true
      
      volumes:
      - name: config
        configMap:
          name: argocd-image-updater-config
      - name: ssh-keys
        secret:
          secretName: argocd-ssh-keys
          optional: true
          defaultMode: 0600
      
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
# Service for metrics (optional)
apiVersion: v1
kind: Service
metadata:
  name: argocd-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: metrics
  selector:
    app.kubernetes.io/name: argocd-image-updater
