name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "frontend/**"
      - "Dockerfile*"
      - ".github/workflows/build-and-push.yml"

env:
  REGISTRY: your-registry
  BACKEND_IMAGE: your-registry/backend
  FRONTEND_IMAGE: your-registry/frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Get current git tag or commit short SHA for versioning
    - name: Generate image tag
      id: meta
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
        else
          TAG=v0.0.0-${{ github.run_number }}
        fi
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "Image tag: $TAG"
    
    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.BACKEND_IMAGE }}:latest
          ${{ env.BACKEND_IMAGE }}:${{ steps.meta.outputs.tag }}
        cache-from: type=registry,ref=${{ env.BACKEND_IMAGE }}:buildcache
        cache-to: type=registry,ref=${{ env.BACKEND_IMAGE }}:buildcache,mode=max
    
    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.frontend
        push: true
        tags: |
          ${{ env.FRONTEND_IMAGE }}:latest
          ${{ env.FRONTEND_IMAGE }}:${{ steps.meta.outputs.tag }}
        cache-from: type=registry,ref=${{ env.FRONTEND_IMAGE }}:buildcache
        cache-to: type=registry,ref=${{ env.FRONTEND_IMAGE }}:buildcache,mode=max
    
    - name: Image digest
      run: echo "Backend and Frontend images pushed successfully"

  notify-argocd:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Trigger ArgoCD sync (optional)
      run: |
        echo "Images pushed to registry. ArgoCD Image Updater will detect and update manifests automatically."
      continue-on-error: true
